spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/evaluation?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null




server:
  servlet:
    context-path: /evaluation


logging:
  level:
    com.yeafel.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
